### ISSUE TITLE
Checklist for client repo changes

### ISSUE THREAD

**Issue by pagarevijayy** [pagarevijayy/ecom-eragap-frontend#5]
### Checklist

- [ ]  Browser Data (store related info)
- [ ] Manifest file (+ related images)
- [ ] Environment variables
- [ ] Client specific UI changes

Client-specific changes and their respective values are stored in client repo itself in form of issues
